#ifndef PUBLICINTERFACE_GLOBAL_H
#define PUBLICINTERFACE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(PUBLICINTERFACE_LIBRARY)
#  define PUBLICINTERFACE_EXPORT Q_DECL_EXPORT
#else
#  define PUBLICINTERFACE_EXPORT Q_DECL_IMPORT
#endif

#endif // PUBLICINTERFACE_GLOBAL_H
