/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-109896-g156ca86569-20230221"
#endif /* AVUTIL_FFVERSION_H */
